name: Bug report
description: Report a bug.
labels: ["bug"]
assignees: ["xxAROX"]

body:
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: The operating system you are playing.
      options: ["Android","IOS","MacOS","Fire TV","Windows 10","PlayStation","Nintendo Switch","XBOX","Windows Phone","Linux"]
    validations:
      required: true

  - type: input
    id: expected_result
    attributes:
      label: "Expected result"
      description: "What were you expecting to happen?"
    validations:
      required: true

  - type: input
    id: actual_result
    attributes:
      label: "Actual result"
      description: "What actually happened?"
    validations:
      required: true

  - type: textarea
    id: steps_to_repoduce
    attributes:
      label: "Steps to reproduce the issue"
      value: |
        1. ...
        2. ...
    validations:
      required: true
